function createfigure1(X1, Y1, Size1, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9, Y10, Y11, Y12, Y13, Y14)
%CREATEFIGURE1(X1, Y1, Size1, Y2, Y3, Y4, Y5, Y6, Y7, Y8, Y9, Y10, Y11, Y12, Y13, Y14)
%  X1:  vector of scatter x data
%  Y1:  vector of scatter y data
%  SIZE1:  vector of scatter size data
%  Y2:  vector of scatter y data
%  Y3:  vector of scatter y data
%  Y4:  vector of scatter y data
%  Y5:  vector of scatter y data
%  Y6:  vector of plot y data
%  Y7:  vector of scatter y data
%  Y8:  vector of scatter y data
%  Y9:  vector of scatter y data
%  Y10:  vector of scatter y data
%  Y11:  vector of scatter y data
%  Y12:  vector of scatter y data
%  Y13:  vector of scatter y data
%  Y14:  vector of plot y data

%  Auto-generated by MATLAB on 04-Jan-2023 18:48:44

% Create figure
figure1 = figure('OuterPosition',[202.6 280.2 982.4 554.8]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,Size1,'Marker','.');

% Create scatter
scatter(X1,Y2,Size1,'Marker','.');

% Create scatter
scatter(X1,Y3,Size1,'Marker','.');

% Create scatter
scatter(X1,Y4,Size1,'Marker','.');

% Create scatter
scatter(X1,Y5,Size1,'Marker','.');

% Create plot
plot(X1,Y6,'DisplayName','Actual','LineWidth',1.5);

% Create ylabel
ylabel('Speed (km/h)');

% Create xlabel
xlabel('Time (s)');

% Create title
title('RHS Radar Velocity Measurements');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 6.8]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[30 90]);
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.815768022758264 0.876268992720755 0.0857438024410532 0.0412371141804037]);

% Create axes
axes2 = axes;
hold(axes2,'on');

% Create scatter
scatter(X1,Y7,Size1,'Marker','.');

% Create scatter
scatter(X1,Y8,Size1,'Marker','.');

% Create scatter
scatter(X1,Y9,Size1,'Marker','.');

% Create scatter
scatter(X1,Y10,Size1,'Marker','.');

% Create scatter
scatter(X1,Y11,Size1,'Marker','.');

% Create scatter
scatter(X1,Y12,Size1,'Marker','.');

% Create scatter
scatter(X1,Y13,Size1,'Marker','.');

% Create plot
plot(X1,Y14,'DisplayName','Actual','LineWidth',1.5);

% Create ylabel
ylabel('Speed (km/h)');

% Create xlabel
xlabel('Time (s)');

% Create title
title('LHS Radar Velocity Measurements');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 6.8]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[30 90]);
hold(axes2,'off');
% Create legend
legend2 = legend(axes2,'show');
set(legend2,...
    'Position',[0.353225941463684 0.84329901758977 0.0857438024410531 0.0412371141804043]);

% Create textarrow
annotation(figure1,'textarrow',[0.768233387358185 0.80226904376013],...
    [0.301245250431779 0.250431778929188],'String',{'Car 1'});

% Create textarrow
annotation(figure1,'textarrow',[0.7032414910859 0.660533157752567],...
    [0.375542801241597 0.293209467908263],'String',{'Car 2'});

% Create textarrow
annotation(figure1,'textarrow',[0.33130824554295 0.361516578876283],...
    [0.321057460611677 0.240860879415096],'String',{'Car 2'});

% Create textarrow
annotation(figure1,'textarrow',[0.228128376553214 0.204170043219881],...
    [0.371090927813819 0.291962722685614],'String',{'Car 1'});

% Create textarrow
annotation(figure1,'textarrow',[0.381544604267963 0.346648770934629],...
    [0.682052723715374 0.769591185253836],'String',{'Car 2'});

% Create textarrow
annotation(figure1,'textarrow',[0.176511007563479 0.230677674230146],...
    [0.712145622784177 0.79647895611751],'String',{'Car 1'});

% Create textarrow
annotation(figure1,'textarrow',[0.634895833333333 0.684895833333333],...
    [0.699027215087456 0.812206702266943],'String',{'Car 2'});

% Create textarrow
annotation(figure1,'textarrow',[0.820548858725013 0.792944692058346],...
    [0.716536813922356 0.801938523324065],'String',{'Car 1'});

