function [allData, scenario, sensors] = MSC_cars_sim()
%ADT_SIM - Returns sensor detections
%    allData = ADT_SIM returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = ADT_SIM optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 9.12 (R2022a) and Automated Driving Toolbox 3.5 (R2022a).
% Generated on: 14-Mar-2022 11:34:07

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
[sensors, numSensors] = createSensors(scenario);
% INS - inertial navigation system
allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    time  = scenario.SimulationTime;

    objectDetections = {};
    laneDetections   = [];
    ptClouds = {};
    insMeas = {};
    isValidTime = false(1, numSensors);

    % Generate detections for each sensor
    for sensorIndex = 1:numSensors
        sensor = sensors{sensorIndex};
        [objectDets, isValidTime(sensorIndex)] = sensor(poses, time);
        numObjects = length(objectDets);
        objectDetections = [objectDetections; objectDets(1:numObjects)]; %#ok<AGROW>
    end

    % Aggregate all detections into a structure for later use
    if any(isValidTime)
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release all the sensor objects so they can be used again.
for sensorIndex = 1:numSensors
    release(sensors{sensorIndex});
end

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function [sensors, numSensors] = createSensors(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensors{1} = drivingRadarDataGenerator('SensorIndex', 1, ...
    'UpdateRate', 35.7142857142857, ...
    'MountingLocation', [3.7 0.9 0.2], ...
    'MountingAngles', [80 0 0], ...
    'RangeLimits', [0 70], ...
    'TargetReportFormat', 'Detections', ...
    'RangeRateResolution', 3, ...
    'RangeRateLimits', [0.2 75], ...
    'RangeResolution', 1.5, ...
    'FieldOfView', [30 30], ...
    'Profiles', profiles);
sensors{2} = drivingRadarDataGenerator('SensorIndex', 2, ...
    'UpdateRate', 35.7142857142857, ...
    'MountingLocation', [3.7 -0.9 0.2], ...
    'MountingAngles', [-80 0 0], ...
    'RangeLimits', [0 70], ...
    'TargetReportFormat', 'Detections', ...
    'RangeRateResolution', 3, ...
    'RangeRateLimits', [0.2 75], ...
    'RangeResolution', 1.5, ...
    'FieldOfView', [30 30], ...
    'Profiles', profiles);
numSensors = 2;

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario('SampleTime', 0.002);

% Add all road segments
roadCenters = [24.9 100.1 0;
    25.14 -100.07 0];
headings = [-90;-90];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'Road');

roadCenters = [25 0 0;
    -5 -0.3 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road1');

roadCenters = [20.1 99.9 0;
    20.1 -0.2 0;
    20.45 -100.06 0];
laneSpecification = lanespec(2, 'Width', 0.925);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road2');

% Add the actors
lHS_Car = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [27 97.7012718576833 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'LHS_Car');
waypoints = [27 97.7012718576833 0;
    27 -98.2 0];
speed = [30;30];
waittime = [0;0];
trajectory(lHS_Car, waypoints, speed, waittime);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [15.56 1.98 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Host');

vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [23.17 -97.89 0], ...
    'Yaw', 90, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'RHS_Car');

